#!/usr/bin/env bash

DOTFILES=~/Dropbox/dotfiles
mkdir ~/bin

ln -s $DOTFILES/emacs.d ~/emacs.d
ln -s $DOTFILES/bak.zshrc ~/.zshrc
#ln -s $DOTFILES/atom ~/.atom

git config --global core.excludesfile ~/$DROPBOX/dotfiles/global_gitignore
# git lg
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
# git ll
git config --global alias.ll "log --pretty=format:'%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]' --decorate --numstat"

# Better diffs (comes from git contrib scripts)
# swap diff-highlight for diff-so-fancy
#git config --global pager.log 'diff-highlight | less'
#git config --global pager.show 'diff-highlight | less'
#git config --global pager.diff 'diff-highlight | less'
# git config --global interactive.diffFilter diff-highlight
#curl https://raw.githubusercontent.com/git/git/master/contrib/diff-highlight/diff-highlight > ~/bin/diff-highlight && chmod +x ~/bin/diff-highlight

# zsh plugins
git clone git://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
git clone https://github.com/djui/alias-tips.git $ZSH_CUSTOM/plugins/alias-tips
git clone git@github.com:Dbz/zsh-kubernetes.git $ZSH_CUSTOM/plugins/zsh-kubernetes
git clone https://github.com/jimeh/zsh-peco-history.git $ZSH_CUSTOM/plugins/zsh-peco-history

# Homebrew packages
brew install ack cloc elixir emacs erlang ffmpeg ghi git go hub leiningen mtr redis sbcl tsung weechat wget peco fzf
/usr/local/opt/fzf/install

brew cask install aerial ngrok

npm i -g spaceship-zsh-theme diff-so-fancy

# use diff-so-fancy for git diffs
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"

# diff-so-fancy suggested colors
# https://github.com/so-fancy/diff-so-fancy/tree/ed8cf1763d38bdd79ceb55a73b9ce7e30f1e184d#improved-colors-for-the-highlighted-bits
git config --global color.ui true

git config --global color.diff-highlight.oldNormal "red bold"
git config --global color.diff-highlight.oldHighlight "red bold 52"
git config --global color.diff-highlight.newNormal "green bold"
git config --global color.diff-highlight.newHighlight "green bold 22"

git config --global color.diff.meta "227"
git config --global color.diff.frag "magenta bold"
git config --global color.diff.commit "227 bold"
git config --global color.diff.old "red bold"
git config --global color.diff.new "green bold"
git config --global color.diff.whitespace "red reverse"
